[platformio]
default_envs = xiao_esp32s3

[env:xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.filesystem = littlefs
board_build.partitions = default_8MB.csv
lib_ldf_mode = chain+
lib_deps =
    h2zero/NimBLE-Arduino @ ^1.4.2
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^7.0.0
    esphome/ESPAsyncWebServer-esphome @ ^3.3.0

[env:xiao_esp32s3_ota]
extends = env:xiao_esp32s3
upload_protocol = espota
upload_port = whisperbridge.local
upload_flags =
    --port=3232
    --auth=password
