[env:xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
lib_extra_dirs = ../../../Common
board_build.filesystem = littlefs
lib_deps =
    esphome/ESPAsyncWebServer-esphome @ ^3
    knolleary/PubSubClient @ ^2
    bblanchon/ArduinoJson @ ^7


[env:native]
platform = native
test_framework = unity
build_flags = -std=c++17
lib_deps = bblanchon/ArduinoJson @ ^7
test_build_src = false
